services:
  multi-strategy:
    image: ghcr.io/unitiny/multi-strategy:latest
    container_name: multi-strategy
    restart: always
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - app-data:/app/persist

volumes:
  app-data:
